name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.2.2
  - jupyter=1.0.0
  - seaborn=0.11.1
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.6.2
  - pyarrow=4.0.0
  - pip:
      - wandb == 0.13.2
      - protobuf==3.20.*